### ISSUE TITLE
Beginner Python Projects

### ISSUE THREAD

**Issue by labesoft** [labesoft/top-projects#1]
Create multiple easy project in python taken from [Top Python Projects](https://data-flair.training/blogs/python-project-ideas). These include:

- [X] Alarm Clock with GUI
- [X] Hangman Game in Python
- [X] Mad Libs Generator Game
- [x] Rock Paper Scissors Game
- [x] Dice Rolling Simulator Game
- [x] Password Generator
- [x] Currency Converter
- [x] Text to Speech
- [x] YouTube Downloader with Pytube
- [x] Message Encode Decode in Python with Tkinter
- [x] Address Book
- [x] Keyboard Jump Game
- [x] Fruit Ninja Game
- [x] COVID-19 Spread Analysis with Flask
- [x] Simple Calculator
- [x] Snake Game
- [x] Library Managememnt System

**Comment by benlapETS** [comment]
Each project must have:

- Its own documentation on the readme.md
- Full code implemented
- Its set of unit tests

It is required to create 1 issue per project to document the workflow

**Comment by benlapETS** [comment]
The procedure for each issue should be:

- [ ] Create the issue with the first (Dataflair) paragraph for the description and this checklist
- [ ] Create the python package (with the init file)
- [ ] Create the main file
- [ ] Create the README file
- [ ] Comment the code (from the project checklist)
- [ ] Implement the code
- [ ] Test the code
- [ ] Complete the readmes for this project
- [ ] Create the pull request
- [ ] Complete the pull request
- [ ] Check the project as completed in #1
