### ISSUE TITLE
Plan (and choose) the 3D library intregration for a rolling dice

### ISSUE THREAD

**Issue by labesoft** [labesoft/top-projects#19]
We need to create the task to execute to be able to develop the Dice rolling simulation game. We also want to choose a good 3D library that will enable good graphics and ease our dev effort.

- [x] Design (Creating assets (Scene, Objects, Textures), Wireframe, Storyboard)
- [ ] Implementation (convert assets to models, add models to the game, code the behaviours)
- [ ] Test & review
- [ ] Loop this to refine the game as required
- [ ] Deploy the game

**Comment by benlapETS** [comment]
I started a local branch dev_panda3d_helloworld which looked nice but I am still undecided what to do next with that, because it didnt convinced me that panda3d is the tool the we absolutely need. I still hesitate between Unity (the best gaming tool , but in C#) and panda3d (not very good, but in pyhon)

**Comment by labesoft** [comment]
We decided to build our dice game with panda3d and based the task scheduling on this [tutorial](https://arsthaumaturgis.github.io/Panda3DTutorial.io/tutorial/prologue.html). There is 17 lessons so it may make us 17 tasks to implement our dice game. The tasks will go as following:

-

**Comment by benlapETS** [comment]
This plan is too much in the implementation details I will amend this. This tutorial has something to inspire but we cannot follow as-is. I would recommand this:

- Creating assets (Scene, Objects, Textures)
- Introduce assets into panda3d game
- Handle the behaviours of the new assets
- Test & review
- Loop this to refine the game as desired

**Comment by labesoft** [comment]
The panda3d plan has failed, this tool is not good enough for our needs. We will switch to Unity.

**Comment by benlapETS** [comment]
The procedure described up here will change a bit while learning how to code/test/deploy/maintain/enhance a game based on the Unity engine.

**Comment by benlapETS** [comment]
I will take this [beginner course](https://learn.unity.com/course/create-with-code?language=en) which is 36h long
