### ISSUE TITLE
Design: Create new assets

### ISSUE THREAD

**Issue by benlapETS** [labesoft/top-projects#23]
Throughout the design step we will add assets required for our game that we will generate with Blender. The results will be documented here before it ends up in the assets folder on the main repository.

**Comment by benlapETS** [comment]
Created a dice:

![dice2](https://user-images.githubusercontent.com/11091581/103779989-6cc5ef80-5002-11eb-9cf6-ad101af7d814.png)

**Comment by benlapETS** [comment]
Created a green felt texture:

![green_felt_texture](https://user-images.githubusercontent.com/11091581/103780592-2d4bd300-5003-11eb-9b84-7f20610a6f7a.png)

**Comment by benlapETS** [comment]
Created a 3D model of a craps table:

![craps_table_carved](https://user-images.githubusercontent.com/11091581/103782912-1064cf00-5006-11eb-96d7-dbd86c993974.png)

**Comment by benlapETS** [comment]
Created a craps table decalc:

![craps_table_decalc](https://user-images.githubusercontent.com/11091581/103783107-4bff9900-5006-11eb-9999-47597c40b84c.png)

**Comment by benlapETS** [comment]
Assembled the craps table:

![craps_table](https://user-images.githubusercontent.com/11091581/103783610-f37ccb80-5006-11eb-9e90-14f8d24d5ff3.png)

**Comment by labesoft** [comment]
We think that there might be more assets to come because we will switch to Unity for developping the game.

**Comment by benlapETS** [comment]
The assets are the same but in Unity assets files
