### ISSUE TITLE
Design: Wireframe the game

### ISSUE THREAD

**Issue by benlapETS** [labesoft/top-projects#24]
This step is to visualize the grapical interface the player will see before it gets integrated to the game which will improve the design of the game.

**Comment by benlapETS** [comment]
The initial state of the game:

![game_init](https://user-images.githubusercontent.com/11091581/103787679-e3b3b600-500b-11eb-9ff9-2ea6d41d53bb.png)

**Comment by benlapETS** [comment]
The pre-mixing state (with a selected dice ready to roll:

![game_premix](https://user-images.githubusercontent.com/11091581/103813009-600ac100-502d-11eb-8d47-458bb2c1f959.png)

**Comment by benlapETS** [comment]
The mixed dice state (optionnal: the player may choose to roll without mixing):

![game_mixed](https://user-images.githubusercontent.com/11091581/103946827-27d6b180-5105-11eb-9e9d-964e5e3f66b6.png)

**Comment by benlapETS** [comment]
One dice roll state:

![game_roll](https://user-images.githubusercontent.com/11091581/103968531-06d88580-5132-11eb-9f25-5e7c4f355059.png)

**Comment by benlapETS** [comment]
The game over state:

![game_over](https://user-images.githubusercontent.com/11091581/103968583-1e177300-5132-11eb-8272-4c1966667eec.png)

**Comment by benlapETS** [comment]
The images has been updated properly

**Comment by labesoft** [comment]
This is exactly what we expected as game high quality 3d images
