### ISSUE TITLE
Design: Storyboard the gameplay

### ISSUE THREAD

**Issue by benlapETS** [labesoft/top-projects#25]
This task documents the different step and state the player will accomplish during the game helping to keep trace of the decision that lead to the design and the design itself before it ends on the main branch.

**Comment by benlapETS** [comment]
Created the storyboard of the first shot of the game with a ppt:

[storyboard.pptx](https://github.com/labesoft/top-projects/files/5790101/storyboard.pptx)

**Comment by labesoft** [comment]
This has been closed too early each scene should be identified on each pptx. Since it causes some ambiquituies not having it
