### ISSUE TITLE
Import our blender design into Unity

### ISSUE THREAD

**Issue by labesoft** [labesoft/top-projects#27]
As our plan to use panda3d prooved to be insufficient for our needs we then go back one step and try to import our blender word to unity. By the way we also need to specify the we won't code in python anymore but in C#.

**Comment by benlapETS** [comment]
This is definetely what I needed, all our 3D design has been exported to Unity and the result is stunning:

![image](https://user-images.githubusercontent.com/11091581/104649055-13a13000-5682-11eb-9067-06cbc64b690c.png)

**Comment by benlapETS** [comment]
This was nearly as easy as dragging and dropping our blender assets into Unity assets. Except for the textures, materials (felt and glass like plastics) and some learning curve with the editor controls. Knowing what plugins would be needed (like HDRP) also took some time.
